--------------------------------------------------------
--  File created - Monday-December-02-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADMIN_TABLE
--------------------------------------------------------

  CREATE TABLE "SYS"."ADMIN_TABLE" 
   (	"ADMIN_USERNAME" VARCHAR2(50 BYTE), 
	"ADMIN_PASSWORD" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYS.ADMIN_TABLE
SET DEFINE OFF;
Insert into SYS.ADMIN_TABLE (ADMIN_USERNAME,ADMIN_PASSWORD) values ('jatin','Jatin$123');
--------------------------------------------------------
--  DDL for Index ADMIN_TABLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."ADMIN_TABLE_PK" ON "SYS"."ADMIN_TABLE" ("ADMIN_USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ADMIN_TABLE
--------------------------------------------------------

  ALTER TABLE "SYS"."ADMIN_TABLE" MODIFY ("ADMIN_USERNAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."ADMIN_TABLE" MODIFY ("ADMIN_PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SYS"."ADMIN_TABLE" ADD CONSTRAINT "ADMIN_TABLE_PK" PRIMARY KEY ("ADMIN_USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
