--------------------------------------------------------
--  File created - Monday-December-02-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BILLS
--------------------------------------------------------

  CREATE TABLE "SYS"."BILLS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USER_NAME" VARCHAR2(255 BYTE), 
	"BILL_COST" NUMBER(10,2), 
	"DATE_TIME" VARCHAR2(200 BYTE), 
	"BILL_NAME" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYS.BILLS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C007494
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."SYS_C007494" ON "SYS"."BILLS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BILLS
--------------------------------------------------------

  ALTER TABLE "SYS"."BILLS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."BILLS" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."BILLS" MODIFY ("BILL_COST" NOT NULL ENABLE);
  ALTER TABLE "SYS"."BILLS" MODIFY ("DATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."BILLS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BILLS
--------------------------------------------------------

  ALTER TABLE "SYS"."BILLS" ADD CONSTRAINT "FK_USER_NAME" FOREIGN KEY ("USER_NAME")
	  REFERENCES "SYS"."USERS" ("USERNAME") ENABLE;
