--------------------------------------------------------
--  File created - Monday-December-02-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MOVIE_SHOWS
--------------------------------------------------------

  CREATE TABLE "SYS"."MOVIE_SHOWS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SHOW_NAME" VARCHAR2(255 BYTE), 
	"TICKET_COST" NUMBER(10,2), 
	"SEATS_LEFT" NUMBER(*,0), 
	"CITY" VARCHAR2(255 BYTE), 
	"SHOW_TIME" VARCHAR2(20 BYTE), 
	"BILL_TYPE" VARCHAR2(20 BYTE), 
	"BILL_NAME" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYS.MOVIE_SHOWS
SET DEFINE OFF;
Insert into SYS.MOVIE_SHOWS (ID,SHOW_NAME,TICKET_COST,SEATS_LEFT,CITY,SHOW_TIME,BILL_TYPE,BILL_NAME) values (29,'Friends',250,50,'New York','2024-12-26',null,null);
Insert into SYS.MOVIE_SHOWS (ID,SHOW_NAME,TICKET_COST,SEATS_LEFT,CITY,SHOW_TIME,BILL_TYPE,BILL_NAME) values (27,'comicstan',250,40,'delhi','2024-12-20 04:30:00',null,null);
Insert into SYS.MOVIE_SHOWS (ID,SHOW_NAME,TICKET_COST,SEATS_LEFT,CITY,SHOW_TIME,BILL_TYPE,BILL_NAME) values (28,'Love Aaj Kl',250,50,'Indore','2024-12-26 18:00:00',null,null);
Insert into SYS.MOVIE_SHOWS (ID,SHOW_NAME,TICKET_COST,SEATS_LEFT,CITY,SHOW_TIME,BILL_TYPE,BILL_NAME) values (18,'Vir Das: Abroad Understanding',700,150,'Mumbai','2024-12-04 20:00:00',null,null);
Insert into SYS.MOVIE_SHOWS (ID,SHOW_NAME,TICKET_COST,SEATS_LEFT,CITY,SHOW_TIME,BILL_TYPE,BILL_NAME) values (19,'Zakir Khan: The Love Aaj Kal Tour',650,110,'Delhi','2024-12-05 19:30:00',null,null);
Insert into SYS.MOVIE_SHOWS (ID,SHOW_NAME,TICKET_COST,SEATS_LEFT,CITY,SHOW_TIME,BILL_TYPE,BILL_NAME) values (21,'Dangal',500,120,'Mumbai','2024-12-01 18:30:00',null,null);
Insert into SYS.MOVIE_SHOWS (ID,SHOW_NAME,TICKET_COST,SEATS_LEFT,CITY,SHOW_TIME,BILL_TYPE,BILL_NAME) values (22,'Sholay',400,85,'Delhi','2024-12-01 20:00:00',null,null);
Insert into SYS.MOVIE_SHOWS (ID,SHOW_NAME,TICKET_COST,SEATS_LEFT,CITY,SHOW_TIME,BILL_TYPE,BILL_NAME) values (23,'Kabhi Khushi Kabhie Gham',450,100,'Bangalore','2024-12-02 15:00:00',null,null);
Insert into SYS.MOVIE_SHOWS (ID,SHOW_NAME,TICKET_COST,SEATS_LEFT,CITY,SHOW_TIME,BILL_TYPE,BILL_NAME) values (24,'Lagaan',550,75,'Chennai','2024-12-02 17:30:00',null,null);
Insert into SYS.MOVIE_SHOWS (ID,SHOW_NAME,TICKET_COST,SEATS_LEFT,CITY,SHOW_TIME,BILL_TYPE,BILL_NAME) values (25,'3 Idiots',600,60,'Kolkata','2024-12-03 19:00:00',null,null);
--------------------------------------------------------
--  DDL for Index SYS_C007480
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."SYS_C007480" ON "SYS"."MOVIE_SHOWS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MOVIE_SHOWS
--------------------------------------------------------

  ALTER TABLE "SYS"."MOVIE_SHOWS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."MOVIE_SHOWS" MODIFY ("SHOW_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."MOVIE_SHOWS" MODIFY ("TICKET_COST" NOT NULL ENABLE);
  ALTER TABLE "SYS"."MOVIE_SHOWS" MODIFY ("SEATS_LEFT" NOT NULL ENABLE);
  ALTER TABLE "SYS"."MOVIE_SHOWS" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "SYS"."MOVIE_SHOWS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
