--------------------------------------------------------
--  File created - Monday-December-02-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TRANSACTIONS
--------------------------------------------------------

  CREATE TABLE "SYS"."TRANSACTIONS" 
   (	"TRANSACTION_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USERNAME" VARCHAR2(255 BYTE), 
	"SHOW_ID" NUMBER(*,0), 
	"SHOW_NAME" VARCHAR2(255 BYTE), 
	"COST" NUMBER(10,2), 
	"DATE_TIME" VARCHAR2(255 BYTE), 
	"COUNT" NUMBER(*,0), 
	"BOOKED_SEATS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYS.TRANSACTIONS
SET DEFINE OFF;
Insert into SYS.TRANSACTIONS (TRANSACTION_ID,USERNAME,SHOW_ID,SHOW_NAME,COST,DATE_TIME,COUNT,BOOKED_SEATS) values (17,'kd',19,'Zakir Khan: The Love Aaj Kal Tour',6500,'29-NOV-24 10.36.33.096805700 AM',null,10);
--------------------------------------------------------
--  DDL for Index SYS_C007487
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."SYS_C007487" ON "SYS"."TRANSACTIONS" ("TRANSACTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TRANSACTIONS
--------------------------------------------------------

  ALTER TABLE "SYS"."TRANSACTIONS" MODIFY ("TRANSACTION_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TRANSACTIONS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TRANSACTIONS" MODIFY ("SHOW_ID" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TRANSACTIONS" MODIFY ("SHOW_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TRANSACTIONS" MODIFY ("COST" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TRANSACTIONS" MODIFY ("DATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."TRANSACTIONS" ADD PRIMARY KEY ("TRANSACTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANSACTIONS
--------------------------------------------------------

  ALTER TABLE "SYS"."TRANSACTIONS" ADD CONSTRAINT "FK_USERNAME" FOREIGN KEY ("USERNAME")
	  REFERENCES "SYS"."USERS" ("USERNAME") ENABLE;
  ALTER TABLE "SYS"."TRANSACTIONS" ADD CONSTRAINT "FK_SHOWS_ID" FOREIGN KEY ("SHOW_ID")
	  REFERENCES "SYS"."MOVIE_SHOWS" ("ID") ON DELETE CASCADE ENABLE;
