--------------------------------------------------------
--  File created - Monday-December-02-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "SYS"."USERS" 
   (	"USERNAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(255 BYTE), 
	"ACCOUNT_BALANCE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYS.USERS
SET DEFINE OFF;
Insert into SYS.USERS (USERNAME,PASSWORD,ACCOUNT_BALANCE) values ('aanchal','Aanchal@1234',2061);
Insert into SYS.USERS (USERNAME,PASSWORD,ACCOUNT_BALANCE) values ('test1','Jatin$123',0);
Insert into SYS.USERS (USERNAME,PASSWORD,ACCOUNT_BALANCE) values ('amrita','amrita',1910);
Insert into SYS.USERS (USERNAME,PASSWORD,ACCOUNT_BALANCE) values ('USER1','123',null);
Insert into SYS.USERS (USERNAME,PASSWORD,ACCOUNT_BALANCE) values ('rajanya','123',null);
Insert into SYS.USERS (USERNAME,PASSWORD,ACCOUNT_BALANCE) values ('test2','Jatin$123',0);
Insert into SYS.USERS (USERNAME,PASSWORD,ACCOUNT_BALANCE) values ('Aanchal','Aanchal@123',90);
Insert into SYS.USERS (USERNAME,PASSWORD,ACCOUNT_BALANCE) values ('test3','123',null);
Insert into SYS.USERS (USERNAME,PASSWORD,ACCOUNT_BALANCE) values ('harshita','123',200);
Insert into SYS.USERS (USERNAME,PASSWORD,ACCOUNT_BALANCE) values ('hello','world',211);
Insert into SYS.USERS (USERNAME,PASSWORD,ACCOUNT_BALANCE) values ('snxid','njecb',null);
Insert into SYS.USERS (USERNAME,PASSWORD,ACCOUNT_BALANCE) values ('testing','123',null);
Insert into SYS.USERS (USERNAME,PASSWORD,ACCOUNT_BALANCE) values ('priyanka','Priyanka123**',100);
Insert into SYS.USERS (USERNAME,PASSWORD,ACCOUNT_BALANCE) values ('kd','Kd@dhawan1',43500);
Insert into SYS.USERS (USERNAME,PASSWORD,ACCOUNT_BALANCE) values ('Harcharan','Harcharan@123',0);
--------------------------------------------------------
--  DDL for Index SYS_C007455
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS"."SYS_C007455" ON "SYS"."USERS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "SYS"."USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "SYS"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SYS"."USERS" ADD PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
